### ISSUE TITLE
荷造り

### ISSUE THREAD

**Issue by osyoyu** [osyoyu/hikkoshi2020#3]
ダンボール20箱ぐらいあれば良い？

**Comment by graph226** [comment]
トラックあるならなるべくダンボールにしないほうが楽という知見があります (出すのがだるい)

**Comment by pikatenor** [comment]
120サイズx10ではやや不足という感じだった（スーパーに駆け込んで数枚取ってきた） 90サイズx5枚ほど追加であると贅沢につかえて良かったと思う

**Comment by pikatenor** [comment]
120、まあまれに入らないものも出てくるんだが、個人で運ぶとなるとデカすぎても運ぶのがだるいので入らないものは諦めて手で持つのが吉

**Comment by osyoyu** [comment]
- 100サイズ x 4
- 120サイズ長型 x 10 (内寸 450x350x300) 
- 140サイズ長型 x 3 (内寸 600x405x354)

を買ってきたが、100サイズに本を詰めていたらあっという間に枯渇してしまった。

**Comment by osyoyu** [comment]
120の底面が100と同じサイズ（つまり高いだけの上位互換）なので、120を数枚買い足してきた。あと140で入らなかったもののために160も

- 120サイズ長型 x 5 (内寸 550x300x300)
- 160サイズ x 2 (内寸 620x428x450)

**Comment by osyoyu** [comment]
今気づいたんだけど、「120サイズ 長型」の段ボールが2種類存在していた…… どうしてこんなことに……

**Comment by osyoyu** [comment]
## ここまでの荷造りの感想
押し入れ・本棚を中心に進めている。

100・120サイズ（底面が450x350）のサイズを中心に使っている。いろいろ入るようで意外と入らない。縦の長さがほぼ350mmの判型の本が結構あって、それがピタッと収まってくれるのはそこそこ便利。CDケースとかは入るけど結構すわりが悪い。
荷造りの際に重要なのは箱の底面の大きさで、高さは二の次なので、底面が120と同じ大きさの100はただの下位互換だった。

**Comment by osyoyu** [comment]
24箱では足りなかったので6箱追加

**Comment by osyoyu** [comment]
生前の部屋の姿を撮っておくとよかったかもしれない。記録として

**Comment by osyoyu** [comment]
本陣は最終的に32箱前後ぐらいになった。多すぎる。

あと5-6箱分ぐらいの荷物は残ってるけど、これはシュッと詰められるので終わりということにする。


## 箱の使い勝手
最初にたくさん買った 450x350x300 が大きすぎも小さすぎもせず、結局一番使い勝手が良かった。
（とはいえ、CDケースとかは全然入らなくて諦めたので、底面は500x350（アートのMサイズ）ぐらいがいいのかも）

550x300x300 は短辺が小さすぎてダメ。
